### PR TITLE
Add section for the Pangeo Use Case

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
# Summary

Add a page explaining how to deploy Pangeo using EGI Services.

---

**Related issue :**

### CODE REVIEW

**Comment by gwarf** [comment]
Hi @sebastian-luna-valero , this PR is still in draft mode, is it expected? We will review it once it will no more be marked as a draft.

**Comment by sebastian-luna-valero** [comment]
Thanks for checking, @gwarf 

Indeed, it's a still a work in progress and will mark it as ready for review in due course.

**Comment by enolfc** [comment]
@sebastian-luna-valero can we push this forward? ;)

**Comment by sebastian-luna-valero** [comment]
Sorry for the late reply.

We are drafting docs over at https://github.com/pangeo-data/pangeo-eosc/

I will move the final version here asap.

**Comment by gwarf** [comment]
@enolfc, @glarocca, @andrea-manzi can we merge this PR?

**Comment by gwarf** [comment]
> @enolfc, @glarocca, @andrea-manzi can we merge this PR?

Hi guys, any chance to provide feedback on this one?

**Review by glarocca — APPROVED** [review]
LGTM

**Review by enolfc — APPROVED** [review]
LGTM

**Pull request merged**
