### PR TITLE
Document APEL accounting for HTCondor-CE

### LINKED ISSUE #545: Document APEL accounting for HTCondor-CE
# Short Description of the issue

Since the HTCondor-CE maintainers are not part of EGI, they would like to have HTCondor-CE APEL primarily documented as part of EGI docs instead of the HTCondor-CE docs. This aligns with HTCondor-CE APEL being effectively maintained by volunteers from EGI.

There is pre-existing documentation and references on the topic that could be aggregated in the EGI docs. As the most recent maintainer of HTCondor-CE APEL, I've volunteered to do so.

# Summary of proposed changes

I'll add a new section in the "Providers" / "High Throughput Compute" docs and link it appropriately.

### PR DESCRIPTION
**Pull request by maxfischer2781**
# Summary

This PR adds a new section into "Providers" / "High Throughput Compute" on "APEL Accounting for HTCondor-CE".

---

**Related issue :**

Closes #545.

### CODE REVIEW

**Review by paolini78 — COMMENTED** [review]
thanks for adding this documentation.
Let's wait for Baptiste to merge the changes.

**Review by paolini78 — COMMENTED** [review]
fixed a link

**Comment by maxfischer2781** [comment]
Thanks for the the first look and fixing the link. I've checked the preview, everything looks as intended; ready for review.

**Review by gwarf — APPROVED** [review]
Thanks @maxfischer2781, LGTM!
I've pushed few small changes, relating to cosmetics, providing link to upstream, suggesting to use the version from UMD and linking from the service page.

**Review by paolini78 — COMMENTED** [review]
thanks for the fixes

**Pull request merged**
