### PR TITLE
Owners of the infrastructure are now listed in IM

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
# Summary

xref: https://github.com/grycap/im-dashboard/pull/357

---

**Related issue :**

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Oh sorry, this is only available in the dev instance at the moment.

I will ping back once the change is merged.

**Comment by enolfc** [comment]
@sebastian-luna-valero should we move this to draft?

**Comment by sebastian-luna-valero** [comment]
Thanks for the reminder.

Actually, this is now available in production so I would suggest to merge.

Unless @micafer would like to add more details

**Comment by micafer** [comment]
> Thanks fo the reminder.
> 
> Actually, this is now available in production so I would suggest to merge.
> 
> Unless @micafer would like to add more details

I have nothing to add.

**Review by enolfc — APPROVED** [review]
👍

**Pull request merged**
