### PR TITLE
creation of the ROD pages

### PR DESCRIPTION
**Pull request by paolini78**
we create the section describing the ROD activity moving the content of https://wiki.egi.eu/wiki/Regional_Operator_on_Duty

### CODE REVIEW

**Review by paolini78 — COMMENTED** [review]
thanks

**Review by paolini78 — COMMENTED** [review]
thanks

**Review by paolini78 — COMMENTED** [review]
thanks

**Review by paolini78 — COMMENTED** [review]
thanks

**Comment by gwarf** [comment]
(oops, I forgot to approve when merging, got confused when bypassing the check for gitleaks)

**Pull request merged**
