### PR TITLE
remove data orchestrator and openrdm docs

### PR DESCRIPTION
**Pull request by andrea-manzi**
…for now)

# Summary

---

**Related issue :**

### CODE REVIEW

**Review by gwarf — COMMENTED** [review]
I'm not fond of keeping old/legacy/unused cruft, If we are not sure we will use this again, we could just delete them, in the end they will always still be in the git history, should we need to revive them at some point.

**Review by gwarf — APPROVED** [review]
LGTM

**Comment by gwarf** [comment]
@glarocca, @enolfc, @andrea-manzi should we just merge this now?

**Comment by andrea-manzi** [comment]
yes :-)

**Comment by gwarf** [comment]
@glarocca can you please approve this change?

**Review by glarocca — APPROVED** [review]
LGTM

**Pull request merged**
