### PR TITLE
Create release-schedule.md

### PR DESCRIPTION
**Pull request by ggrein**
# Summary

GGUS Release Schedule

---

**Related issue :**

### CODE REVIEW

**Comment by gwarf** [comment]
@ggrein seems my email came late, but I'm not at all sure about the relevance of this for this doc site, if we include this info here we would need to do it for all central services, and I don't think it's planned nor that we have it.
Can't it be moved to GGUS release_notes page itself?

**Comment by ggrein** [comment]
Why not?
I think this is a good idea.

**Comment by gwarf** [comment]
I'm currently not sure what's the purpose of this page, and I don't think we agreed/need to collect this info for other services.
docs.egi.eu is more meant to cover documentation about the services, mainly for people to use them, and I don't (yet?) see the benefit of moving this page here.
If you really would like to share this kind of schedule maybe it could be easier/cleaner to have it with https://ggus.eu/index.php?mode=release_notes ?
It would also be easier for you to update it when releasing a new version.

**Comment by gwarf** [comment]
Closing this PR, it was agreed to put this in the release_notes page of GGUS.

**Pull request closed without merging**
