### PR TITLE
Add subpage for Infrastructure Manager

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
# Summary

Adding a dedicated subpage for Infrastructure Manager.

Also updated a few links.

---

**Related issue :**

### CODE REVIEW

**Comment by gwarf** [comment]
Some errors are due to the fact that we finally purged content from https://egi-federated-cloud-integration.readthedocs.io/ (to avoid having people still refer to it).
Could you try to also fix the links? (here or in another PR that would be merged before this one)

**Review by gwarf — APPROVED** [review]
LGTM!

**Comment by sebastian-luna-valero** [comment]
FYI: Levente is working on a Getting Started guide and that's why I haven't touched the introductory text for Cloud Compute as the entry point for IM.

**Review by enolfc — APPROVED** [review]
LGTM. Thanks @sebastian-luna-valero!

**Pull request merged**
