### PR TITLE
First attempt to fix the owners

### PR DESCRIPTION
**Pull request by enolfc**
# Summary

Bring CST members into the user section

---

**Related issue :**

### CODE REVIEW

**Comment by enolfc** [comment]
Mainly a starting point
@glarocca please let us know who from CST should be in charge for some of the sections

**Review by gwarf — APPROVED** [review]
LGTM

**Comment by gwarf** [comment]
@enolfc should we merge this first update?

**Comment by enolfc** [comment]
> @enolfc should we merge this first update?

Yes, @glarocca if you have any suggestions on people we can add them in a following PR

**Pull request merged**
