### PR TITLE
updating the list of required services

### PR DESCRIPTION
**Pull request by paolini78**
from https://wiki.egi.eu/w/index.php?title=NGI_services_in_GOCDB&oldid=112084
removed the links to that page

### CODE REVIEW

**Review by gwarf — APPROVED** [review]
LGTM

**Review by paolini78 — COMMENTED** [review]
thanks for the corrections

**Review by sebastian-luna-valero — APPROVED** [review]
Thanks!

**Review by paolini78 — COMMENTED** [review]
thanks

**Comment by gwarf** [comment]
I will bypass the gitleaks report for now (already did too many unrelated fixes), we may wait for https://github.com/github/super-linter/issues/3407 to be fixed to make use of this feature.

**Pull request merged**
