### PR TITLE
Declare prettier as dependency of pre-commit hook

### LINKED ISSUE #640: Prettier should be declared as pre-commit dependency
# Add prettier as extra dependency of pre-commit

The `prettier` pre-commit hook which formats code requires the prettier executable to be present. Typically this can be run retrieving prettier on the fly `npx prettier`  but pre-commit doesn't know about that. 

So, we need to declare it as `additional_dependencies` in `.pre-commit-config.yaml`

### PR DESCRIPTION
**Pull request by brucellino**
# Summary

This adds prettier as a dependency of the prettier pre-commit hook.

Turns out that the prettier configuration wants to be exported as a module, so the `additional-dependencies` in the pre-commit config don't get picked up.

I've declared explicit versions of Prettier for the pre-commit hook and added a `devDependencies` key in the `package.json` which was missing.

**Related issue :**

- https://github.com/prettier/prettier/issues/15388

Closed #640

### CODE REVIEW

**Comment by brucellino** [comment]
woops. Looks like I didn't discard the intermediate commits. Hope you squash this?

**Comment by brucellino** [comment]
@sebastian-luna-valero ready for review.

**Review by sebastian-luna-valero — APPROVED** [review]
Working for me, many thanks!

**Review by enolfc — APPROVED** [review]
Working locally so good to go

**Pull request merged**
