### PR TITLE
Replace EGI with EOSC marketplace for DIRAC

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
# Summary

---

**Related issue :**

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Actually, https://docs.egi.eu/users/compute/orchestration/workload-manager/#the-egi-workload-manager-web-portal also needs updating. Not sure where to start :)

**Comment by gwarf** [comment]
For the access request, shouldn't we align with, or redirect to, https://docs.egi.eu/users/getting-started/#pilot-your-application ?
Or do we have a specific interest in going via the EOSC Marketplace? Like maybe liaising with the Workload Manager team to have them configure the access?

**Comment by sebastian-luna-valero** [comment]
I believe that's the case since I was member of `vo.access.egi.eu` and I had to open a GGUS ticket to get my access configured. So either the EOSC Marketplace is a trigger (which would also help us accounting interest for the service) or we need another trigger to configure access to DIRAC after enrolling into `vo.access.egi.eu`.

**Review by gwarf — APPROVED** [review]
LGTM

**Review by enolfc — APPROVED** [review]
Let's go for it

**Pull request merged**
