### PR TITLE
Configuration Database: give a few hints on using the API

### LINKED ISSUE #338: Review/complete Configuration Database access documentation
Review/complete Configuration Database access documentation

### PR DESCRIPTION
**Pull request by gwarf**
Configuration Database: give a few hints on using the API.
Close #338

### CODE REVIEW

**Comment by gwarf** [comment]
@gregcorbett can you please check if https://docs.egi.eu/documentation/548/internal/configuration-database/api/ makes sense?
I'm still slightly confused about the naming and usage of the two APIs, with the public/read that may also request authentication, and the write that may be used only for requesting access to some info containing things like personal data.

**Review by paolini78 — COMMENTED** [review]
thanks, they look good

**Comment by gregcorbett** [comment]
> @gregcorbett can you please check if https://docs.egi.eu/documentation/548/internal/configuration-database/api/ makes sense? I'm still slightly confused about the naming and usage of the two APIs, with the public/read that may also request authentication, and the write that may be used only for requesting access to some info containing things like personal data.

Will do, apologies for the delay in responding.

**Comment by gregcorbett** [comment]
Hi all, I've made a sugeested update here: https://github.com/gwarf/documentation/pull/5

**Comment by gwarf** [comment]
Thanks a lot @gregcorbett , @paolini78 can you please review/approve the PR?

**Review by paolini78 — COMMENTED** [review]
thanks, I'm fine with the changes.

**Review by paolini78 — APPROVED** [review]
approving

**Pull request merged**
