### PR TITLE
Link to marketplace updated to EOSC

### PR DESCRIPTION
**Pull request by crsndr**
# Summary

---

**Related issue :**

### CODE REVIEW

**Review by gwarf — COMMENTED** [review]
Thanks @crsndr, I'm a bit surprised, was it discussed/agreed that we should point to EOSC Marketplace instead of EGI Marketplace (that we control) for offering/presenting our services?

**Review by gwarf — CHANGES_REQUESTED** [review]
I would first like to get a confirmation that it was agreed/decided to switch links to point to the EOSC MP and not to the EGI one.

**Comment by crsndr** [comment]
@gwarf yes we need to check as after talking with @sebastian-luna-valero I understood that this is still under discussion. Who do you think is the best person to ask?

**Comment by gwarf** [comment]
> @gwarf yes we need to check as after talking with @sebastian-luna-valero I understood that this is still under discussion. Who do you think is the best person to ask?

Would suggest to discuss this with Diego.

**Comment by crsndr** [comment]
Ok. I think he's out of office for this week so if you could keep this on hold for now.

**Comment by sebastian-luna-valero** [comment]
I discussed this with @glarocca a couple of weeks ago.

There are ongoing discussions to upgrade the EGI Marketplace so I think that we need to keep the existing link as is.

**Comment by gwarf** [comment]
> I discussed this with @glarocca a couple of weeks ago.
> 
> There are ongoing discussions to upgrade the EGI Marketplace so I think that we need to keep the existing link as is.

Indeed. So let's close this PR and open a new one later if needed (and updating all references to the MP to point to the EOSC one if it was decided).

**Pull request closed without merging**
