### PR TITLE
[Check-in] Replace links to wiki.egi.eu

### PR DESCRIPTION
**Pull request by nikosev**
# Summary

This PR replaces the hyper links to wiki.egi.eu.

### CODE REVIEW

**Comment by gwarf** [comment]
488 got merged, (you are welcome for the conflicts :) ). It may be quicker to restart from scratch...

**Comment by nikosev** [comment]
@gwarf I have resolved the conflicts, most of them where resolved by PR#488, but I found one URL (https://wiki.egi.eu/wiki/GOCDB/PI/get_user_method) which should be replaced.
I couldn't find the new place of this guide, so I removed the hyperlink.

**Comment by paolini78** [comment]
@nikosev the page https://wiki.egi.eu/wiki/GOCDB/PI/get_user_method haven't been moved to a new location yet so for the moment you can keep the link to that.

**Comment by nikosev** [comment]
Thank you @paolini78 for letting me know!
I'm closing this PR since there is no any other change in this PR

**Pull request closed without merging**
