### PR TITLE
Update docs about deleting downtimes starting in 24 hours or less

### PR DESCRIPTION
**Pull request by gregcorbett**
# Summary

This PR will update the docs about deleting GOCDB downtimes starting in less than 24 hours or less. Being able to delete such downtimes was a bug that we fixed in GOCDB 5.9.0: https://github.com/GOCDB/gocdb/pull/279

### CODE REVIEW

**Comment by gwarf** [comment]
So nobody is supposed to be able to cancel a downtime?

**Comment by gregcorbett** [comment]
Not within 24 hours of it starting, the rational being the downtime has been read/logged in other systems - such as the monitoring system.

**Review by paolini78 — APPROVED** [review]
thanks for correcting that.

**Review by gwarf — APPROVED** [review]
LGTM

**Pull request merged**
