### PR TITLE
Update links under users, providers and internal sections

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
# Summary

A couple of links in https://docs.egi.eu/providers/joining/federated-resource-centre/ need updating.

---

**Related issue :**

### CODE REVIEW

**Review by gwarf — APPROVED** [review]
LGTM

**Review by paolini78 — APPROVED** [review]
thanks

**Comment by gwarf** [comment]
Thanks @sebastian-luna-valero, can you please also address the other files under `content/en/providers/joining/` unfortunately it seems the checks in the reorganisation PR missed those broken links :/

You can use the following command to test things locally:

```shell
docker run -v ${PWD}:/tmp:ro --rm -i ghcr.io/tcort/markdown-link-check:stable \
  --config /tmp/.github/linters/mlc_config.json --quiet --verbose \
  /tmp/content/en/providers/joining/core-service/_index.md
```

**Review by gwarf — CHANGES_REQUESTED** [review]
Other files under `content/en/providers/joining` have to be fixed too.

**Comment by gwarf** [comment]
Thanks, found some more in other directories:
Under  `en/users/` there are the following ones: 
content/en/users/dev-env/binder/_index.md
content/en/users/dev-env/notebooks/kernels/matlab/_index.md
content/en/users/dev-env/notebooks/_index.md
content/en/users/getting-started/cli/_index.md
content/en/users/getting-started/architecture/_index.md
content/en/users/getting-started/_index.md
en/users/compute/orchestration/ec3/apps/ecas/_index.md
content/en/users/data/management/open-rdm/_index.md
content/en/users/data/management/rucio/admin/_index.md
content/en/users/data/management/rucio/getting-started/_index.md
content/en/users/_index.md

For some it may be needed to ask some colleagues

**Comment by gwarf** [comment]
Then in the `en/internal` directory I found those one that I will fix and push to your PR:
content/en/internal/operations-portal/service-information/_index.md
content/en/internal/getting-started/_index.md
content/en/internal/monitoring/service-information/_index.md
content/en/internal/helpdesk/account-and-privileges/_index.md
content/en/internal/_index.md

**Comment by gwarf** [comment]
@enolfc, @andrea-manzi  for https://github.com/EGI-Federation/documentation/blob/main/content/en/users/data/management/open-rdm/_index.md?plain=1#L30, https://openbis.ch/ is apparently down, is it known/expected?

**Comment by gwarf** [comment]
@andrea-manzi apparently rucio moved away from readthedocs, so I've updated the links as I could, please have a look

**Review by gwarf — APPROVED** [review]

**Pull request merged**
