### PR TITLE
Minor amedments in docs

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
# Summary

Replace 1GB with 10GB in the documentation about persistent storage for notebooks.

---

**Related issue :** https://github.com/EGI-Federation/documentation/issues/213

### CODE REVIEW

**Review by enolfc — APPROVED** [review]
👍  Welcome @sebastian-luna-valero

**Comment by sebastian-luna-valero** [comment]
Many thanks @enolfc

**Comment by enolfc** [comment]
@gwarf this seems not to be showing up in docs.egi.eu.

I see the action was executed without issues: https://github.com/EGI-Federation/documentation/runs/2583077315 but the last commit on the EGI-Federation.github.io repo is from April 30. The only thing in between is the rename to `main`, so I guess this didn't work as expected.

**Comment by enolfc** [comment]
found it: Pages was using `master` branch, changed it to `main`. Changes are now live

**Comment by gwarf** [comment]
Thanks @enolfc, seems I forgot about this!

**Pull request merged**
