### PR TITLE
How to list all owned VMs in fedcloud

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
# Summary

Addresses the comments in https://github.com/EGI-Federation/documentation/issues/496

---

**Related issue :** https://github.com/EGI-Federation/documentation/issues/496

### CODE REVIEW

**Comment by gwarf** [comment]
Should there be a link to our documentation on setting up fedcloudclient?

**Comment by sebastian-luna-valero** [comment]
Sorry, you are right! I have just added a link.

**Review by gwarf — APPROVED** [review]
Thanks a lot, LGTM!

**Review by enolfc — APPROVED** [review]
Thanks @sebastian-luna-valero! LGTM

**Pull request merged**
