### PR TITLE
Tutorial template

### PR DESCRIPTION
**Pull request by thebe14**
A template for new tutorials. Please note that this template links to the getting started pages (currently draft), which should be updated with meaningful content by the time the first tutorial based on this template is published.

---

**Related issue :**

### CODE REVIEW

**Comment by andrea-manzi** [comment]
@gwarf do you think it's fine to have template with empty sections about the tutorial part published on the documentation site?

**Comment by thebe14** [comment]
Everything under Tutorials is currently marked as draft

**Comment by andrea-manzi** [comment]
ok sorry, i missed that they were marked as draft and not processed by hugo, this is why i made the comment. If they are not shown until they are ready it's fine for me :-)

**Comment by thebe14** [comment]
@gwarf anything else needed for this to be merged? Andrea C (and others) is waiting to create his tutorial based on it.

**Comment by gwarf** [comment]
> @gwarf anything else needed for this to be merged? Andrea C (and others) is waiting to create his tutorial based on it.

In fact I was waiting for a review of someone involved in this. But we can mage, we can update this later if needed.

**Review by gwarf — APPROVED** [review]

**Pull request merged**
