### PR TITLE
Improve `Client Migration to Keycloak` instructions

### PR DESCRIPTION
**Pull request by nikosev**
# Summary

This PR introduces the following changes:

- Break `Endpoints` table per environment using tabpanex
- Add section for the intrspection endpoint in migration guide
- Add "Common Issues" section
- Add sub-sections in `Client Migration to Keycloak`
- Update endpoints with the Keycloak OIDC Endpoints in OpenStack guide

### CODE REVIEW

**Comment by gwarf** [comment]
Thanks, I feel the tapanex is easier to read. Could you pleaes also replace the table at the end of https://docs.egi.eu/documentation/461/providers/check-in/sp/#general-information ?
Same for info on https://docs.egi.eu/documentation/461/providers/check-in/idp/ ?

**Comment by gwarf** [comment]
Duh, the link check are successful, the pages disappeared: https://github.com/EGI-Federation/documentation/runs/7007222970?check_suite_focus=true#step:4:43

**Review by gwarf — APPROVED** [review]
LGTM, thanks!
@vardizzo-lab, please have a look.

**Review by vardizzo-lab — APPROVED** [review]
OK.

**Pull request merged**
