### PR TITLE
X509 proxy and uk e science ca update

### PR DESCRIPTION
**Pull request by Thysk**
A small edit to the getting started documentation, as the UK eScience certificate information, link, and adding it to the container was missed by a user.

Also made small change to config to use the x509_proxy rather than x509

### CODE REVIEW

**Comment by gwarf** [comment]
Not related to the changes, but I think you need to adapt your GitHub workflow, this PR is again including some commits that, while at least they don't change unintended files, should probably not be there: 
Screenshot 2022-05-11 at 15 12 21

This may help: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

@enolfc , @andrea-manzi letting you review the PR.

**Comment by Thysk** [comment]
Thanks for that link, I will take a look, and I did notice that list of commits that weren't helpful

**Comment by gwarf** [comment]
> Thanks for that link, I will take a look, and I did notice that list of commits that weren't helpful

No worries, cf https://xkcd.com/1597/ ^^ :)
image

**Review by gwarf — APPROVED** [review]
LGTM

**Review by andrea-manzi — APPROVED** [review]
LGTM

**Pull request merged**
