### PR TITLE
New API documentation for AppDB

### PR DESCRIPTION
**Pull request by enolfc**
# Summary

Content extracted from https://wiki.egi.eu/wiki/EGI_AppDB_REST_API_v1.0 and reformatted to match docs.egi.eu style

---

**Related issue :**

### CODE REVIEW

**Comment by gwarf** [comment]
Is the authentication really/still/only relying on EGI SSO, cf https://docs.egi.eu/documentation/533/users/compute/cloud-compute/appdb/#authenticated-access ? No Check-in integration?

https://github.com/EGI-Federation/documentation/pull/533/files#diff-0007fe32ed37e4bd12caa862a669d09c0de6e7099a86453819f86f52bdcf766aR257

> - forwarding the [EGI SSO](https://www.egi.eu/sso/) credentials of their users,

Doesn't look that great to suggest sending EGI SSO credentials to something that isn't EGI SSO. Is this still the case?

**Comment by enolfc** [comment]
> Can we wait for an update on that part before merging?

@wvkarageorgos @nakos can you comment on this?

**Comment by wvkarageorgos** [comment]
Hi, I've made a PR on Enol's feature branch, with the changes for the Authenticated Access section

**Review by gwarf — APPROVED** [review]
Thanks, LGTM!
Looks fine to merge this version with this content.

**Pull request merged**
