### PR TITLE
Update links on k8s docs

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
# Summary

Fixes https://github.com/EGI-Federation/documentation/issues/231

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Hi team, this is ready for review.

Thanks,
Sebastian

**Review by enolfc — APPROVED** [review]
Thanks!

I think we may need a new Github action to check for links no longer working so this situation does not come back again

**Comment by sebastian-luna-valero** [comment]
I think this is already in place? 

This passed: https://github.com/EGI-Federation/documentation/runs/2837928344

This didn't: https://github.com/EGI-Federation/documentation/runs/2837861878

It made amend my commit this morning ;)

**Comment by sebastian-luna-valero** [comment]
Ok, so something is not working properly.

Earlier I updated the links to what I thought was correct: https://github.com/EGI-Federation/documentation/pull/232/commits/7a25553c9e54b7b11639ad67cbe008f1873ca2f6 but the `markdown-link-check` failed: 

https://github.com/EGI-Federation/documentation/runs/2837861878

I reverted back to what it was with the following commit: https://github.com/EGI-Federation/documentation/pull/232/commits/3ac0417dadc5f9f92f07066d5d5c0f30c791b1e3 and this time the `markdown-link-check` went fine:

https://github.com/EGI-Federation/documentation/runs/2837928344

If I go back to https://docs.egi.eu/users/cloud-container-compute/k8s/ to check the new links, links are broken again.

Any ideas?

**Comment by gwarf** [comment]
In order to test/debug links, it's handy to run the docs locally, as documented in https://docs.egi.eu/about/contributing/git/#running-the-site-locally and  https://github.com/EGI-Federation/documentation#testing-the-site-locally 

Did you try this?

**Comment by sebastian-luna-valero** [comment]
You guessed correctly, I was being lazy and not building the site locally :D 

I have now built the site locally and here is the problem. Applying https://github.com/EGI-Federation/documentation/pull/232/commits/7a25553c9e54b7b11639ad67cbe008f1873ca2f6 to the local site clone, I confirm that the links work correctly in the local site. However the `markdown-link-check` [failed when I pushed that commit to the repo](https://github.com/EGI-Federation/documentation/runs/2837861878) .

Am I missing something basic here again?

**Comment by gwarf** [comment]
@sebastian-luna-valero please have a look at #235 and check if it seems to work fine for you.
Let's also see if it fixes the k8s links once for all.

**Pull request merged**
