### PR TITLE
Use prettier action to auto-format code in pull requests

### PR DESCRIPTION
**Pull request by gwarf**
Use prettier action to auto-format code in pull requests using https://github.com/marketplace/actions/prettier-action
Auto-format is done before the lint.

### CODE REVIEW

**Comment by gwarf** [comment]
So it's not ultra clear if it could easily work with PR from forks:
* https://github.com/creyD/prettier_action/issues/54#issuecomment-858891671
* https://github.com/stefanzweifel/git-auto-commit-action#advanced-uses

I've seen advice to run it when pushing to master.

**Comment by thebe14** [comment]
Just a note here. Most of our .md files are not regular markdown files, but contain Hugo-specific stuff, which is sometimes sensitive to formatting. We should test this auto-formatter before we use it on the main documentation repo.

**Comment by gwarf** [comment]
> Just a note here. Most of our .md files are not regular markdown files, but contain Hugo-specific stuff, which is sometimes sensitive to formatting. We should test this auto-formatter before we use it on the main documentation repo.

I think that basically every file that @enolfc and I have been editing went through prettier and are working fine.
AFAIK even the landing page that includes some custom/unusual html code didn't had anything broken.

Have you some special page in mind that we should carefully consider?

**Comment by brucellino** [comment]
This is likely deprecated by #635

**Comment by enolfc** [comment]
Closing as we have #635 and #641 merged

**Pull request closed without merging**
