### PR TITLE
Add link to EOS in grid storage section

### PR DESCRIPTION
**Pull request by andrea-manzi**
# Summary

---

**Related issue :**

### CODE REVIEW

**Comment by andrea-manzi** [comment]
@gwarf has the linter changed? i got errors from other pages already pushed

**Comment by gwarf** [comment]
> @gwarf has the linter changed? i got errors from other pages already pushed

I'm not sure if something changed, but the errors that are reported seems valid, so I'm fixing them, and we will merge once all is good.

**Comment by gwarf** [comment]
So the remaining error on github.com is a known error due to their server configuration. I will enable PR preview to confirm all links/changes are fine and then we can merge.

**Review by gwarf — APPROVED** [review]
Thanks, LGTM!

**Comment by andrea-manzi** [comment]
thanks a lot!

**Pull request merged**
