### PR TITLE
Add default capacity allocation back

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
# Summary

---

**Related issue :**

### CODE REVIEW

**Review by glarocca — COMMENTED** [review]
Approve changes

**Review by glarocca — APPROVED** [review]

**Review by gwarf — APPROVED** [review]
LGTM

**Review by enolfc — COMMENTED** [review]
for Notebooks this is not true :) Does it really make sense to put the numbers here?

**Review by enolfc — APPROVED** [review]
LGTM

**Pull request merged**
