### PR TITLE
[Check-in] Migrate Production endpoints to Keycloak based OP

### PR DESCRIPTION
**Pull request by nikosev**
# Summary

This PR introduces the following changes:

- Update OIDC endpoints of the Production instance of Check-in OP
- Update the example response of device code flow
- Fix misspelled words and code style
- Update guidelines for `Protocol Specific` options on OpenStack guide

### CODE REVIEW

**Comment by nikosev** [comment]
@gwarf This PR depends on Enol's [PR#463](https://github.com/EGI-Federation/documentation/pull/463).
I will rebase my PR after merging PR#463 in order to fix the conflicts and the failed checks

**Review by vardizzo-lab — APPROVED** [review]
OK

**Comment by enolfc** [comment]
Ready for fixing issues as #463 is now merged.

**Comment by gwarf** [comment]
The errors on the links are apparently some false negative, tested locally and links are working well. Not sure what is failing here, but we can probably merge.

**Comment by gwarf** [comment]
> The errors on the links are apparently some false negative, also tested locally and links are working well, like on the preview. Not sure what is failing here, but we can probably merge.

I see that some links are in the form `(../../cloud-compute/openstack/aai/#client-migration-to-keycloak )`  instead of `(../../cloud-compute/openstack/aai#client-migration-to-keycloak), not sure if this would change the test.

**Pull request merged**
