### PR TITLE
Give permissions to write

### PR DESCRIPTION
**Pull request by enolfc**
# Summary

Try to make the build preview work again
---

**Related issue :** #685

### CODE REVIEW

**Review by gwarf — APPROVED** [review]
LGTM

**Comment by enolfc** [comment]
still does not build previews :(

**Comment by gwarf** [comment]
Wasn't the issue that it was building, but not deploying? In fact I don't think write is needed for the build workflow.

**Comment by enolfc** [comment]
should we revert this one then?

**Comment by gwarf** [comment]
Did it via #692.

**Pull request merged**
