### PR TITLE
Improve Chipster docs

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
# Summary

PR to slightly improve the documentation for Chipster.

@glarocca please review.

---

**Related issue :**

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Strange, I have run `` and I still get:
```
/github/workspace/content/en/users/applications-on-demand/_index.md:152:81 MD013/line-length Line length [Expected: 80; Actual: 145]
```
Sorry, let me have a look.

**Comment by sebastian-luna-valero** [comment]
@glarocca this is ready for review. All tests passing now.

**Comment by glarocca** [comment]
Approve the PR

**Review by glarocca — APPROVED** [review]
Approve the changes

**Pull request merged**
