### PR TITLE
Update Datahub images to the latest available version

### PR DESCRIPTION
**Pull request by andrea-manzi**
# Summary

---

**Related issue :**

### CODE REVIEW

**Comment by andrea-manzi** [comment]
i accidentally added an WIP of the datahub tutorial page, that is marked as draft so not showed anyway

**Comment by andrea-manzi** [comment]
reverted unwanted commit

**Review by gwarf — APPROVED** [review]
Cool, LGTM!

**Comment by gwarf** [comment]
@andrea-manzi  OK for you to merge it  now, following the check of the preview?

**Comment by andrea-manzi** [comment]
yes good thanks!

**Pull request merged**
