### PR TITLE
Enforce link checking

### PR DESCRIPTION
**Pull request by enolfc**
# Summary

- Force checking every link
- Weekly schedule checks for links 

---

**Related issue :** #603

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
I only see the below now:

```bash
FILE: ./content/en/users/compute/cloud-compute/dynamic-dns/_index.md
[✖] https://www.noip.com/integrate/request → Status: 404

7 links checked.

ERROR: 1 dead links found!
[✖] https://www.noip.com/integrate/request → Status: 404
```

**Review by sebastian-luna-valero — APPROVED** [review]
Thank you very much!

**Comment by enolfc** [comment]
we are green! @gwarf could you check the PR?

**Comment by enolfc** [comment]
@andrea-manzi could you check this one?

**Comment by enolfc** [comment]
> now that you checked all files i see that the check Links step lasts 11 min. is that fine?

maybe we should check all files only in the scheduled run? @gwarf

**Comment by sebastian-luna-valero** [comment]
That's a good idea, thanks!

**Review by andrea-manzi — APPROVED** [review]
thanks! LGTM

**Pull request merged**
