### PR TITLE
Replace static table with new cvmfs-monitor

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
# Summary

@jose-caballero what do you think?

---

**Related issue :**

### CODE REVIEW

**Comment by jose-caballero** [comment]
Do not replace it. The table includes links to the organisations/experiments, which are not included in the monitoring.

**Comment by sebastian-luna-valero** [comment]
ok @jose-caballero but would it be ok to link to the [CVMFS monitor](http://cvmfs-release01.gridpp.rl.ac.uk/cvmfsmonitor/) after the static table?

on the other hand, it would also be a good idea to show the links to the organisations/experiments in the dynamic table shown by the [CVMFS monitor](http://cvmfs-release01.gridpp.rl.ac.uk/cvmfsmonitor/)

**Comment by jose-caballero** [comment]
adding the link should be ok

**Comment by jose-caballero** [comment]
Making changes for Confluence is a nightmare. All those built-in checks are more a problem than a solution.

**Comment by gwarf** [comment]
> Making changes for Confluence is a nightmare. All those built-in checks are more a problem than a solution.

Confluence?

We are moving to a new check stack, and it's the one of the first real PR with it, so we have to fix some initial setup.

But we think it's helpful to have checks, even if it can need some effort indeed at some point in time :)

**Review by gwarf — APPROVED** [review]
LGTM.
I merged various fixes, to address issues with the new mega-linter setup.

**Pull request merged**
