### PR TITLE
add link to documentation for the client setup

### PR DESCRIPTION
**Pull request by jose-caballero**
# Summary

---

**Related issue :** https://ggus.eu/?mode=ticket_info&ticket_id=168616

### CODE REVIEW

**Review by sebastian-luna-valero — APPROVED** [review]
Many thanks!

**Review by sebastian-luna-valero — COMMENTED** [review]
Ah sorry, the link is pointing to the configuration of the CVMFS client, but I think it should first point to the installation: https://cvmfs.readthedocs.io/en/latest/cpt-quickstart.html ?

**Review by jose-caballero — COMMENTED** [review]
Use the right link

**Review by sebastian-luna-valero — APPROVED** [review]
Thanks!

**Review by gwarf — APPROVED** [review]
LGTM

**Pull request merged**
