### PR TITLE
Replace port number 31443

### PR DESCRIPTION
**Pull request by EGI-ILM**
Port 31443 does not work any more and it has been replaced by 443. The documentation has been changed accordingly

### CODE REVIEW

**Review by enolfc — APPROVED** [review]
👍 Thanks!

**Comment by enolfc** [comment]
@gwarf is there a way to avoid the spell checker inside code blocks?

**Comment by enolfc** [comment]
Forcing merge as spelling errors are from command outputs and should not be changed

**Comment by gwarf** [comment]
> @gwarf is there a way to avoid the spell checker inside code blocks?

Don't know, would have to check docs/conf. Merging as you did is fine with me.

**Pull request merged**
