### PR TITLE
integration fixes

### PR DESCRIPTION
**Pull request by enolfc**
# Summary

Fix some of the issues found by sites during integration. 
Also deal with #260

﻿- Use production Check-in
- Add mapping.json info
- Fix file name

---

**Related issue :** #260

### CODE REVIEW

**Review by gwarf — APPROVED** [review]
LGTM, cool to see things being fixed using feedback from sites.

**Comment by gwarf** [comment]
The error on line length is a bit surprising, I thought it was disabled due to https://github.com/EGI-Federation/documentation/blob/main/.github/linters/.markdownlint.json#L2.

**Comment by gwarf** [comment]
Or maybe the error was only on the trailing spaces and the line length was just a warning: https://github.com/EGI-Federation/documentation/runs/3535464617#step:4:107

**Comment by enolfc** [comment]
> Or maybe the error was only on the trailing spaces and the line length was just a warning: https://github.com/EGI-Federation/documentation/runs/3535464617#step:4:107

🤷 no idea, I just assume everything the linter spits to me needs to be fixed

**Comment by gwarf** [comment]
> > Or maybe the error was only on the trailing spaces and the line length was just a warning: https://github.com/EGI-Federation/documentation/runs/3535464617#step:4:107
> 
> 🤷 no idea, I just assume everything the linter spits to me needs to be fixed

Thank you for being nice with him ;) Let's see on a next PR how it goes with the line length.

**Pull request merged**
