### PR TITLE
Update link to VO list in Operations Portal

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
# Summary

As of version 6.0 of the Operations Portal the list of VOs is browsable without authentication.

This PR just updates the existing link in the docs with the new one.

---

**Related issue :**

### CODE REVIEW

**Comment by andrea-manzi** [comment]
mmm, https://operations-portal.egi.eu/ is down?

**Comment by enolfc** [comment]
> mmm, https://operations-portal.egi.eu/ is down?

Not just down, for me it complains about being unable to resolve !?

**Comment by sebastian-luna-valero** [comment]
Same here.

Apologies for the linting errors. I found one more reference that needs updating. Please wait until I push it.

Let me also try to setup local testing before pushing as an exercise on this PR.

**Comment by sebastian-luna-valero** [comment]
Please merge.

**Review by gwarf — COMMENTED** [review]
This `/vo/a/list` path looks a bit weird, but indeed it seems to grant access to the user list without having to authenticate while `/vo` that is linked from the `VO List` menu entry required auth.

From where did you get this URL? I'm wondering if we need to clarify this with the service provider.

**Comment by sebastian-luna-valero** [comment]
I visited https://operations-portal.egi.eu/ and clicked on the "VO List" button:

imagen

xref: https://jira.egi.eu/browse/EGIREQ-49

**Pull request merged**
