### PR TITLE
First content for CVMFS

### PR DESCRIPTION
**Pull request by jose-caballero**
First version of documentation for CVMFS.

### CODE REVIEW

**Review by gwarf — CHANGES_REQUESTED** [review]
Thanks for this PR @jose-caballero !

This documentation space is meant to cover documentation on this specific service from an EGI-focused point of view, and while we are waiting for the tests and a more complete review, could you please already change the path to `content-distribution` and the title to only "Content Distribution" as it's how this service is currently named in the EGI Service portfolio? 

Could you also please include a `service-information/_index.md` page, you can look at the one for the Configuration Database to get an example.
Thanks!

**Comment by jose-caballero** [comment]
Hi @gwarf

I have updated the file with 2 changes:

- Fixed the linter errors. 
- Changed the title as you suggested. Quick question, where can I see the EGI portfolio? The original title I used is the name of the service in the EOSC portal. 

You are asking also to change the "path". I don't know what that "path" is in this context. 

You also mentioned a "service-information" page. This documentation is meant to be just for users. I don't currently have anything else. So let's go with the current content, so the corresponding JIRA ticket in the WP6 can be closed, and then we can think about improving it after that. 

Thanks a lot.
Cheers,
Jose

**Comment by gwarf** [comment]
Dear Jose,
The porfolio that contains all services in the various phases is not accessible publicly it's in our Sevice Management System and access is currently limited, but this "Content Distribution" has been present into it since long.
Public information on services can be found on https://www.egi.eu/services/ and https://www.egi.eu/internal-services/. We expect that the Content Distribution will be added at some point.

If you related to this [STFC CVMFS Content Distribution Service
](https://marketplace.eosc-portal.eu/services/stfc-cvmfs-content-distribution-service) seems to be about the STFC/UKRI service and how it could be offered to third parties, so If you want to document an STFC service itself it may have to be done at another location. docs.egi.eu is meant to focus on the instance/access provided to and via EGI.

Thus I don't think that the privacy policy you link is the appropriate one for this case, and we are more expecting to have a privacy policy with EGI Foundation as a controller, and UKRI as a processor on our behalf.

I will update your PR to add the service-information page and review the content, but we prefer to start from a clean version and make improvement after.

**Comment by gwarf** [comment]
Hi Jose, I'm willing to push some change, but apparently you may not allow maintainers to push to your PR, can you have a look?
You may be able to refer to https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Comment by jose-caballero** [comment]
I have just allowed edits by maintainers.

**Comment by gwarf** [comment]
> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

I was able to edit via GitHub, but I still can't push from the CLI, maybe there are branch restrictions or other settings preventing the push?:
Screenshot 2022-02-03 at 14 55 56

That said it may not be worth the effort to dig into this right now as the main things to be fixed before merging a first version are the following:
* renaming the name of the folder containing the doc (`git mv cvmfs content-distribution` should be enough)
* then sorting out the the privacy policy and AUP you mention: I don't think the ones you provided are relevant in the context of the service procured by RAL to EGI, so I would suggest to remove those references and only add the proper ones once they will be ready. I think @CatalinCondurache may also have discussed about this. From EGI side I should be able to draft privacy policies with EGI as Controller, as we do for other EGI central services. Example for Check-in: https://aai.egi.eu/privacy.html

**Comment by andrea-manzi** [comment]
@jose-caballero is it ok the apply the changes suggested by @gwarf ? the new privacy policies is under definition and in any case we don't need to include it in the documentation page

**Review by gwarf — APPROVED** [review]

**Comment by gwarf** [comment]
@jose-caballero I've updated the PR as we discussed, renaming the service and removing references to the policies that are indeed not expected to be documented here.
I've sent you a link to the privacy policy draft, so we can sort this our later.
For me this PR seems now ready to be merged.

**Review by enolfc — APPROVED** [review]
:+1:

**Pull request merged**
