### PR TITLE
tech details of the operation portal

### PR DESCRIPTION
**Pull request by paolini78**
page containing the ID card of the service

# Summary

---

**Related issue :**

### CODE REVIEW

**Comment by cyril1er** [comment]
Here is a proposal for the description of the Operations Portal :

### The EGI Operations Portal is a central portal for supporting the operations and coordination of the EGI Infrastructure. It offers a bundle of different capabilities described below .

- **The Broadcast tool** used to contact and inform the different actors of the project for specific problems or global announcements
- **The operations and security dashboards** : Detect, track and follow-up problems and incident on the resource centers
 - **The VO Management tools** : Register,  update, consult  information about virtual communities
 - **The Metrics module**: Provide metrics and indicators about the different activities of the project linked to VOs, users 
 - **The SLA module**: provide information about performances for the cloud sites and SLA Violations for different group of services .

**Comment by cyril1er** [comment]
For the service information page :
- Source code : https://gitlab.in2p3.fr/opsportal/sf3
- Issue tracker : https://gitlab.in2p3.fr/opsportal/sf3/-/issues

**Comment by gwarf** [comment]
Thanks, this looks good!
We can merge this first version once the tests will have succeed, thanks for your input @cyril1er.

**Review by gwarf — APPROVED** [review]
LGTM 🚀

**Pull request merged**
